"""remove genre column in film table

Revision ID: 27a6b90d4f0f
Revises: cc2a39b8bf11
Create Date: 2021-10-28 14:54:31.910831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a6b90d4f0f'
down_revision = 'cc2a39b8bf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_film_genre', table_name='film')
    op.drop_column('film', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('film', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_film_genre', 'film', ['genre'], unique=False)
    # ### end Alembic commands ###
