"""init

Revision ID: cc2a39b8bf11
Revises: 
Create Date: 2021-10-28 14:46:20.943795

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cc2a39b8bf11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.create_index(op.f('ix_film_director'), 'film', ['director'], unique=False)
    op.create_index(op.f('ix_film_genre'), 'film', ['genre'], unique=False)
    op.create_index(op.f('ix_film_id'), 'film', ['id'], unique=False)
    op.create_index(op.f('ix_film_name'), 'film', ['name'], unique=False)
    op.create_index(op.f('ix_film_released_year'), 'film', ['released_year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_film_released_year'), table_name='film')
    op.drop_index(op.f('ix_film_name'), table_name='film')
    op.drop_index(op.f('ix_film_id'), table_name='film')
    op.drop_index(op.f('ix_film_genre'), table_name='film')
    op.drop_index(op.f('ix_film_director'), table_name='film')
    op.alter_column('film', 'id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    autoincrement=True)
    op.create_table('song',
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('released_year', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('director', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='song_pkey')
                    )
    # ### end Alembic commands ###
